{
 "title": "air-quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Sensor readings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "The humidity sent from the ESP32",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"hum\" and\n    r._field == \"value\"\n  )"
    },
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"hum\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "The temperature sent from the ESP32",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"temp\" and\n    r._field == \"value\"\n  )"
    },
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"temp\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "description": "The RSSI sent from the ESP32",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"rss\" and\n    r._field == \"value\"\n  )"
    },
    {
     "query": "from(bucket: \"air-quality\")\n  |> range(start: -10h)\n  |> filter(fn: (r) =>\n    r._measurement == \"rss\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 } }
 ]
}